/* SUBQUERY 실습 */
--1) 각 직원 급여가 부서별 평균 급여보다 높은 직원들의 이름과 급여
SELECT EMP_NAME, SALARY,DEPT_CODE
FROM EMPLOYEE E1
WHERE E1.SALARY >= (SELECT AVG (SALARY) 
FROM EMPLOYEE E2
--WHERE E2.DEPT_CODE = E1.DEPT_CODE
GROUP BY DEPT_CODE);

SELECT DEPT_CODE,AVG (SALARY)
FROM EMPLOYEE E2
GROUP BY DEPT_CODE;


--3) D5 부서의 평균 급여보다 높은 급여를 받는 직원들의 이름 조회
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEE WHERE DEPT_CODE='D5');

--4) 급여 300 이상인 직원 중 가장 낮은 급여 직원 이름과 급여
SELECT  EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE WHERE SALARY>=3000000);


--SELECT 에서 작성하는 서브쿼리
--예시 3
-- 각 직급 이름별로 평균 급여 조회

SELECT JOB_NAME, (SELECT AVG(SALARY) FROM EMPLOYEE E
WHERE E.JOB_CODE = J.JOB_CODE
GROUP BY E.JOB_CODE) FROM JOB J;

SELECT JOB_NAME, (SELECT AVG(SALARY)  FROM EMPLOYEE E WHERE E.JOB_CODE = J.JOB_CODE ) FROM JOB J;


/* SELECT 서브 쿼리 실습 */
-- 부서 별 보너스 율 0.2 이상인 직원 수
SELECT D.DEPT_TITLE,  (SELECT COUNT(*) FROM EMPLOYEE E WHERE E.BONUS >=0.2 AND E.DEPT_CODE = D.DEPT_ID) "BONUS COUNT"
FROM DEPARTMENT D;

-- 부서별 최대 최소 급여
SELECT DEPT_TITLE "부서 명", (SELECT MAX(SALARY) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID) "최대 급여", (SELECT MIN(SALARY) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID) "최소 급여"
FROM DEPARTMENT D;

-- 부서별 직원수 조회
SELECT DEPT_TITLE "부서 명", (SELECT COUNT(*) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID) "인원 수"
FROM DEPARTMENT D;

--부서별 직원수 5명 이상인 부서의 부서명과 직원 수 조회

SELECT DEPT_TITLE "부서 명", (SELECT COUNT(*) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID) AS "직원 수"
FROM DEPARTMENT D
WHERE (SELECT COUNT(*) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID) >=5;

