CREATE TABLE DRINK_COMPANY(
    DRINK_ID NUMBER(10,0) PRIMARY KEY,
    DRINK_NAME VARCHAR2(100) NOT NULL,
    DRINK_ADDRESS VARCHAR2(255),
    DRINK_PHONE VARCHAR2(20)
    );
CREATE TABLE SOFTS(
SOFTS_ID NUMBER(10,0) PRIMARY KEY,
SOFTS_NAME VARCHAR2(100) NOT NULL,
PRICE NUMBER(10,2) NOT NULL, 
COMPANY_ID NUMBER(10,0) CONSTRAINT DK_COMPANY REFERENCES DRINK_COMPANY(DRINK_ID) ON DELETE CASCADE
);
DROP TABLE SOFTS;

INSERT INTO DRINK_COMPANY VALUES(1,'고가콜라','서울시 강남구','02-1234-5678');
INSERT INTO DRINK_COMPANY VALUES(2,'벱시','서울시 중구','02-8765-4321');
INSERT INTO SOFTS VALUES(1,'콜라',1500,1);
INSERT INTO SOFTS VALUES(2,'사이다',1200,1);
INSERT INTO SOFTS VALUES(3,'벱시콜라',1000,2);
INSERT INTO SOFTS VALUES(4,'마운틴듀오',2000,2);
SELECT * FROM DRINK_COMPANY;
DELETE FROM DRINK_COMPANY;
SELECT * FROM SOFTS;
