--SQL 연습 출처 : https://blog.naver.com/PostView.naver?blogId=tkdqja8643&logNo=221317891450
SELECT EMP_NAME, JOB_CODE, HIRE_DATE FROM EMPLOYEE2 WHERE HIRE_DATE BETWEEN '2000/02/20' AND '2001/05/01';
SELECT EMP_NAME FROM EMPLOYEE2 WHERE EMP_NAME LIKE '_재%';
SELECT EMP_NAME FROM EMPLOYEE2 WHERE EMP_NAME LIKE '%은%' AND EMP_NAME LIKE '%희%';

SELECT SUBSTR(TO_CHAR(HIRE_DATE,'YYYY'),1) "입사연도", SUBSTR(TO_CHAR(HIRE_DATE,'MM'),1) "입사월" 
FROM EMPLOYEE2;