--WHERE 절 쓸수 없는 경우가 있다.

SELECT EMP_NAME, SALARY *12 AS "연봉"
FROM EMPLOYEE
ORDER BY 연봉 DESC;
-- 별칭으로 ORDERBY 할 수 있으나 WHERE 는 못쓴다

SELECT EMP_NAME, SALARY *12 AS "연봉"
FROM EMPLOYEE
WHERE 연봉 >=50000000;
--에러 발생!

SELECT EMP_NAME,DEPT_CODE,SALARY FROM EMPLOYEE ORDER BY DEPT_CODE ASC, salary DESC;

SELECT EMP_NAME,DEPT_CODE,SALARY FROM EMPLOYEE ORDER BY DEPT_CODE, SALARY DESC;

SELECT EMP_NAME, DEPT_CODE,JOB_CODE FROM EMPLOYEE ORDER BY DEPT_CODE,JOB_CODE DESC,EMP_NAME;