--WHERE 절 쓸수 없는 경우가 있다.

SELECT EMP_NAME, SALARY *12 AS "연봉"
FROM EMPLOYEE
ORDER BY 연봉 DESC;
-- 별칭으로 ORDERBY 할 수 있으나 WHERE 는 못쓴다

SELECT EMP_NAME, SALARY *12 AS "연봉"
FROM EMPLOYEE
WHERE 연봉 >=50000000;
--에러 발생!

SELECT EMP_NAME,DEPT_CODE,SALARY FROM EMPLOYEE ORDER BY DEPT_CODE ASC, salary DESC;

SELECT EMP_NAME,DEPT_CODE,SALARY FROM EMPLOYEE ORDER BY DEPT_CODE, SALARY DESC;

SELECT EMP_NAME, DEPT_CODE,JOB_CODE FROM EMPLOYEE ORDER BY DEPT_CODE,JOB_CODE DESC,EMP_NAME;

/* 별칭 사용하기 */
SELECT EMP_NAME, SALARY * 12 AS "연봉"
FROM EMPLOYEE
ORDER BY 연봉;

SELECT EMP_NAME, SALARY * 12 Y
FROM EMPLOYEE
ORDER BY Y desc;

SELECT EMP_NAME FROM EMPLOYEE ORDER BY EMP_NAME;

-- ORDER BY 실습하기
SELECT EMP_ID "사번", EMP_NAME "이름" FROM EMPLOYEE2
ORDER BY 이름 DESC;

SELECT EMP_ID, EMP_NAME, SALARY AS "월급" FROM EMPLOYEE2 ORDER BY "월급";

SELECT EMPLOYEE2.*,BONUS AS "보너스",SALARY AS "월급" FROM EMPLOYEE2  ORDER BY 보너스 DESC,월급;

select EMP_NAME "이름", DEPT_CODE "부서코드", JOB_CODE "직급코드" from employee2 order by DEPT_CODE, JOB_CODE DESC, EMP_NAME;

SELECT EMP_NAME "이름", SALARY  "급여", SALARY*12+100 "연간 총 수입" FROM EMPLOYEE2 ORDER BY SALARY DESC;
SELECT EMP_NAME "이름", SALARY " 급여" FROM EMPLOYEE2 WHERE SALARY >= 2000000 ORDER BY SALARY DESC;


