-- 이 세개를 집합 연산자 라고 하며, 칼럼의 개수와 데이터 타입이 일치해야 한다.

SELECT EMP_NAME 사람이름, DEPT_CODE, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT
SELECT EMP_NAME, DEPT_CODE 코드, SALARY
FROM EMPLOYEE
WHERE SALARY  > 3000000;

-- INTERSECT 굳이 사용하지 않아도 GROUP BY WHERE 등으로 구분 지을 수 있다.

-- MINUS :  선행 SELECT 결과에서 다음 SELECT 와 겹치는 부분을 제외한 부분
-- UNION :  두 SELECT 결과 합침
-- UNION ALL  : 공통 값을 모두 포함시킨다
SELECT EMP_NAME 사람이름, DEPT_CODE, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_NAME, DEPT_CODE 코드, SALARY
FROM EMPLOYEE
WHERE SALARY  > 3000000;


--이제 뭐 남았게
-- JOIN SUBQUERY CREATE ALTER DROP VIEW SEQUENCE
