/*
OUTER JOIN 외부 조인
- 두 테이블 지정 컬럼값이 일치하지 않는 행도 조인에 포함시킨다.

*/

SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE LEFT OUTER JOIN DEPARTMENT;

--1) LEFT OUTER JOIN
-- 두 테이블 중에서 왼쪽 편에 작성된 테이블의 칼럼 수를 기준으로 JOIN
SELECT EMP_NAME, DEPT_TITLE FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;
-- 왼쪽 테이블의 모든 행이 최종 결과에 포함된다.(값이 없다면 NULL)
-- 이는 ORACLE 표준으로 다음과 같이 적을 수 있다. (+) 를 추가한다
SELECT EMP_NAME, DEPT_TITLE FROM EMPLOYEE,DEPARTMENT WHERE DEPT_CODE = DEPT_ID(+);


--2) RIGHT OUTER JOIN
-- 두 테이블 중에서 오른쪽 편에 작성된 테이블의 칼럼 수를 기준으로 JOIN
SELECT EMP_NAME, DEPT_TITLE FROM EMPLOYEE RIGHT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;
-- 오른쪽 테이블의 모든 행이 최종 결과에 포함된다.(값이 없다면 NULL)
-- 이는 ORACLE 표준으로 다음과 같이 적을 수 있다. (+) 를 추가한다
SELECT EMP_NAME, DEPT_TITLE FROM EMPLOYEE,DEPARTMENT WHERE DEPT_CODE(+) = DEPT_ID;

--3) FULL OUTER JOIN
SELECT EMP_NAME, DEPT_TITLE FROM EMPLOYEE FULL JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;