--DDL Data Definition Language

-- ALTER : 특정 테이블/칼럼에 대한 제약조건/데이터타입을 바꾸거나 이름을 바꾸거나.

-- ALTER TABLE 테이블명 ADD(추가)/MODIFY (수정) / DROP(삭제)
-- 제약 조건 추가 및 삭제

ALTER TABLE SOFTS MODIFY SOFTS_NAME VARCHAR2(200); -- 데이터 타입 변경
ALTER TABLE SOFTS ADD CONSTRAINT SN_K UNIQUE(SOFTS_NAME); --제약조건 추가 
ALTER TABLE SOFTS DROP  CONSTRAINT SN_K; --제약 조건 삭제
ALTER TABLE SOFTS MODIFY SOFTS_NAME VARCHAR(100);


CREATE TABLE DEPT_COPY AS SELECT* FROM DEPARTMENT;
ALTER TABLE DEPT_COPY ADD CONSTRAINT DEPT_PK PRIMARY KEY(DEPT_ID);

-- DPET_COPY 테이블을 수정하겠다.

ALTER TABLE DEPT_COPY ADD CONSTRAINT DEPT_TITLE_U UNIQUE(DEPT_TITLE);

--칼럼 추가 수정 삭제
ALTER TABLE DEPT_COPY ADD DEPT_MANAGER NUMBER(4,0) DEFAULT 999;
SELECT * FROM DEPT_COPY;
ALTER TABLE DEPT_COPY DROP COLUMN DEPT_MANAGER;
DELETE FROM DEPT_COPY WHERE DEPT_ID = 'D0';
ALTER TABLE DEPT_COPY MODIFY CNAME VARCHAR2(20);
ALTER TABLE DEPT_COPY DROP COLUMN CNAME;
ALTER TABLE DEPT_COPY ADD CNAME VARCHAR2(20);


ALTER TABLE DEPT_COPY ADD LNAME VARCHAR2(30) DEFAULT '한국';

ALTER TABLE DEPT_COPY MODIFY DEPT_ID VARCHAR2(3);
ALTER TABLE DEPT_COPY DROP COLUMN CNAME;
ALTER TABLE DEPT_COPY DROP (LNAME);
ALTER TABLE DEPT_COPY DROP COLUMN DEPT_TITLE;
ALTER TABLE DEPT_COPY DROP (LOCATION_ID);