--CONSTRAINT CHECK 
/*
제약조건 CHECK
 - 칼럼에 기록되는 값에 조건을 설정할 수 있다.
 - CHECK (컬럼명 비교연산자 [비교값])
 - [비교값]은 변하는 값이나 함수는 사용할 수 없다.
*/

CREATE TABLE USER_CHECK (
USER_NO NUMBER PRIMARY KEY,
USER_ID VARCHAR2(20) UNIQUE,
USER_PWD VARCHAR2(30) NOT NULL,
USER_NAME VARCHAR2(30),
GENDER VARCHAR2(10) CHECK (GENDER IN('남','여')), --- GENDER에는 '남' 혹은 '여' 만 들어갈 수 있다.
USER_SSN VARCHAR(15)
);
SELECT * FROM USER_CHECK;


INSERT INTO USER_CHECK VALUES (1,'USER01','PWD01','철수팍','남','950728-111111');
INSERT INTO USER_CHECK VALUES (3,'USER03','PWD01','철수팍','남','9528-11133122');
ALTER TABLE USER_CHECK ADD CONSTRAINT SSN_LENGTH_CK CHECK(LENGTH(USER_SSN)>=13); 
DROP TABLE USER_CHECK;